module.exports = [
  {
    name: "华夏律师事务所",
    slug: "huaxia-law-firm",
    city: "北京",
    address: "北京市朝阳区建国路88号SOHO现代城D座1201",
    phone: "+86-10-5860-1234",
    email: "contact@huaxialaw.cn",
    website: "https://www.huaxialaw.cn",
    description:
      "专注于公司治理、并购重组与资本市场的综合性律所，为大型企业和高成长公司提供全流程法律支持。",
    practiceAreas: ["公司治理", "并购重组", "资本市场", "合规管理"],
    tags: ["头部律所", "跨境业务", "资本运营"],
    lawyers: [
      {
        name: "李文斌",
        title: "高级合伙人",
        phone: "+86-138-0000-1234",
        email: "libin@huaxialaw.cn",
        specialties: ["上市合规", "股权激励", "并购交易"],
      },
      {
        name: "张芷晴",
        title: "合伙人",
        phone: "+86-139-0000-5678",
        email: "zhangzhiqing@huaxialaw.cn",
        specialties: ["私募股权", "跨境投融资"],
      },
    ],
  },
  {
    name: "瀚海律师事务所",
    slug: "hisea-law-firm",
    city: "上海",
    address: "上海市浦东新区世纪大道100号环球金融中心35层",
    phone: "+86-21-6888-5566",
    email: "info@hisealaw.com",
    website: "https://www.hisealaw.com",
    description: "提供商业诉讼、国际仲裁与知识产权保护的一体化解决方案。",
    practiceAreas: ["商事诉讼", "国际仲裁", "知识产权", "争议解决"],
    tags: ["争议解决", "知识产权", "跨国企业"],
    lawyers: [
      {
        name: "周骁",
        title: "管理合伙人",
        phone: "+86-137-0000-2468",
        email: "zhouxiao@hisealaw.com",
        specialties: ["涉外仲裁", "商业秘密", "合规调查"],
      },
      {
        name: "林涵",
        title: "资深律师",
        phone: "+86-139-0000-9753",
        email: "linhan@hisealaw.com",
        specialties: ["知识产权维权", "数据合规"],
      },
    ],
  },
  {
    name: "锦程律师事务所",
    slug: "jincheng-law-firm",
    city: "深圳",
    address: "深圳市福田区福华三路168号平安金融中心45层",
    phone: "+86-755-8883-6677",
    email: "service@jinchenglegal.com",
    website: "https://www.jinchenglegal.com",
    description: "深耕新经济、科创企业法律服务，覆盖投融资、知识产权与劳动用工。",
    practiceAreas: ["风险投资", "知识产权", "劳动用工", "企业合规"],
    tags: ["科创企业", "风险投资", "企业合规"],
    lawyers: [
      {
        name: "王瑶",
        title: "合伙人",
        phone: "+86-136-0000-3344",
        email: "wangyao@jinchenglegal.com",
        specialties: ["股权融资", "商业谈判"],
      },
      {
        name: "陈宇翔",
        title: "高级顾问",
        phone: "+86-135-0000-8899",
        email: "chenyx@jinchenglegal.com",
        specialties: ["知识产权战略", "劳动人事"],
      },
    ],
  },
];
